config/routes.rb
Rails.application.routes.draw do
    resources :items
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveRecord::Base
    validates :username, :presence => true
    validates :link, :presence => true
    validates :description, :presence => true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def show
     @item = Item.find(params[:id])
    end

    def new
      @item = Item.new
    end

    def edit
      @item = Item.find(params[:id])
        render :edit
    end

    def update
    @item= Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

    def destroy
       @item = Item.find(params[:id])
       @item.destroy
       redirect_to items_path
     end

    def create
      @item = Item.new(item_params)
      if @item.save
        redirect_to  items_path
      else
        render :new
      end
    end

    private
      def item_params
        params.require(:item).permit(:username, :link, :description)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @item do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :link %>
<%= f.text_field :link %>
<%= f.label :description %>
<%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render "form" %>

app/views/items/index.html.erb
<h1>Items</h1>

  <ul>
    <% @items.each do |item| %>

    <li><%= link_to item.link, item_path(item) %></li>
    <% end %>
  </ul>


    <hr>

    <%= link_to "New Item", new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render "form" %>

app/views/items/show.html.erb
<p1>Username: <%= @item.username %>
  <br /> Link url: <%= @item.link %>
 <br /> Description: <%= @item.description %>
</p1>

<p><%= link_to "Edit", edit_item_path(@item) %></p>
<p><%= link_to "Delete", item_path(@item),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>


  <p><%= link_to "Return to Items", items_path %></p>

app/views/layouts/_errors.html.erb
<% if @item.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>